### ISSUE TITLE
Winetricks fails to remove Mono

### ISSUE THREAD

**Issue by sebi2306** [Winetricks/winetricks#1215]
Winetricks fails to remove Mono because the `--remove` parameter gets passed 2 GUIDs. To fix this either the `grep` should be changed or it should be attempted to remove all GUIDs found one by one.

![Winetricks Oopsie1](https://user-images.githubusercontent.com/6190216/56379848-62096c80-6219-11e9-95b4-5925411f8d19.png)
![Winetricks Oopsie5](https://user-images.githubusercontent.com/6190216/56379849-62096c80-6219-11e9-94e8-fde8347a89ad.png)

**Comment by sebi2306** [comment]
Please ignore my derp

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/7b4e62d481f631452b0f19f0209e48541ebc1f4b

**Comment by sebi2306** [comment]
Yeah, not quite fixed. The problem is that the `--remove` parameter cannot get both GUIDs that get found (one from Mono Runtime and the other one from Windows Support) so it returns 
> uninstaller: The application with GUID '{7290EA95-9F17-58E8-8436-4A532DA0F54E}
{05706910-3B4C-5B10-9F47-759A1CDDECDE}' was not found

**Comment by austin987** [comment]
Are you running from git? For me with wine-4.6-30-gf9301c2b66, I get:

```
+ load_remove_mono ''
++ /home/austin/wine-git/wine uninstaller --list
++ grep 'Wine Mono'
++ grep -v 'Wine Mono Windows Support'
++ cut -f1 '-d|'
+ mono_uuid='{7290EA95-9F17-58E8-8436-4A532DA0F54E}'
+ test '{7290EA95-9F17-58E8-8436-4A532DA0F54E}'
+ /home/austin/wine-git/wine uninstaller --remove '{7290EA95-9F17-58E8-8436-4A532DA0F54E}'
```

and with older wine (wine-3.16):
```
+ load_remove_mono ''
++ /opt/oldwine/wine-3.16/bin/wine uninstaller --list
++ grep 'Wine Mono'
++ grep -v 'Wine Mono Windows Support'
++ cut -f1 '-d|'
+ mono_uuid='{EA50D369-6B67-43BC-8153-C3553B40ABEB}'
+ test '{EA50D369-6B67-43BC-8153-C3553B40ABEB}'
+ /opt/oldwine/wine-3.16/bin/wine uninstaller --remove '{EA50D369-6B67-43BC-8153-C3553B40ABEB}'
```

**Comment by sebi2306** [comment]
The current code breaks when two programs starting with "Wine Mono" get found as it puts their GUIDs together which cannot be parsed by `wine uninstaller --remove`

**Comment by austin987** [comment]
I don't think you're testing the current code, which excludes the support bundle.

**Comment by sebi2306** [comment]
Try to install dotnet40 with Mono installed and tell me if it works. I can do it with the addendums in my PR.

**Comment by sebi2306** [comment]
The PR also accounts for the off chance that someone might have "Wine Mono" and "Wine Mono Runtime" installed for whatever reason. 
I can see now that with only 4.8.1 installed Winetricks works indeed. My fault for having my tests include ancient Mono versions.

**Comment by sebi2306** [comment]
Thanks for your help. You can merge the PR or close it if you want.

**Comment by austin987** [comment]
I'll review it more closely soon. I do like the idea, as it's more foolproof in the future.

I mostly just wanted to make sure that the interim solution worked, because if it didn't, something way worse was going on.

Again, thanks for reporting the initial issue!
