### ISSUE TITLE
installing comctl32 does not work

### ISSUE THREAD

**Issue by Golddouble** [Winetricks/winetricks#1527]
I made this with the gui into a 32 bit prefix.

Message:
![winetricks Error](https://user-images.githubusercontent.com/13977359/79637426-d6098800-817f-11ea-87a7-6c4e39d4f041.png)

Tested with 
-20181203-3 and
-20200412

Edit:
Same issue, when trying to install "d3dx9_36".

**Comment by austin987** [comment]
Should be fixed now. If not, please reopen (and attach the terminal output).

**Comment by Golddouble** [comment]
Tested today with wintericks version:
```
$ winetricks --version
20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d
```

It's still the same.

```
$ winetricks --gui
winetricks GUI enabled, using zenity 3.30.0
Executing mkdir -p /home/user
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d with wine-5.6 (Staging) and WINEARCH=win64
winetricks GUI enabled, using zenity 3.30.0
Executing mkdir -p /home/user/.local/share/wineprefixes
Executing w_do_call comctl32
Executing mkdir -p /home/user/.local/share/wineprefixes
Executing load_comctl32 
Executing wine /home/user/.cache/winetricks/comctl32/cc32inst.exe /T:C:\windows\Temp\_Try2 /c
Wine cannot find the ncurses library (libncurses.so.6).
Executing wine /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/x86/50ComUpd.Exe /T:C:\windows\Temp\_Try2 /c
Wine cannot find the ncurses library (libncurses.so.6).
Executing cp /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/comcnt.dll /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/system32/comctl32.dll
Using native,builtin override for following DLLs: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/winepref$ winetricks --gui
winetricks GUI enabled, using zenity 3.30.0
Executing mkdir -p /home/user
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d with wine-5.6 (Staging) and WINEARCH=win64
winetricks GUI enabled, using zenity 3.30.0
Executing mkdir -p /home/user/.local/share/wineprefixes
Executing w_do_call comctl32
Executing mkdir -p /home/user/.local/share/wineprefixes
Executing load_comctl32 
Executing wine /home/user/.cache/winetricks/comctl32/cc32inst.exe /T:C:\windows\Temp\_Try2 /c
Wine cannot find the ncurses library (libncurses.so.6).
Executing wine /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/x86/50ComUpd.Exe /T:C:\windows\Temp\_Try2 /c
Wine cannot find the ncurses library (libncurses.so.6).
Executing cp /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/comcnt.dll /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/system32/comctl32.dll
Using native,builtin override for following DLLs: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Try2\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Using builtin override for following DLLs when running winecfg.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Try2\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/override-dll.reg
Using builtin override for following DLLs when running explorer.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Try2\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/override-dll.reg
Using builtin override for following DLLs when running iexplore.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Try2\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/override-dll.reg
------------------------------------------------------
comctl32 install completed, but installed file /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/syswow64/comctl32.dll not found
------------------------------------------------------ixes/Try2/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Try2\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Using builtin override for following DLLs when running winecfg.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Try2\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/override-dll.reg
Using builtin override for following DLLs when running explorer.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Try2\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/override-dll.reg
Using builtin override for following DLLs when running iexplore.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Try2\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/temp/_Try2/override-dll.reg
------------------------------------------------------
comctl32 install completed, but installed file /home/user/.local/share/wineprefixes/Try2/dosdevices/c:/windows/syswow64/comctl32.dll not found
------------------------------------------------------
```

**Comment by Golddouble** [comment]
No, it's not solved. It's still the same:

```
user@mx:~
$ winetricks -gui
------------------------------------------------------
unknown option -gui
------------------------------------------------------
user@mx:~
$ winetricks --gui
winetricks GUI enabled, using zenity 3.30.0
Executing mkdir -p /home/user
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 5c62bc038fd3ac7fa1e0d09123c61e1034cc5431719f5a1768dcb4bd91990cca with wine-5.6 (Staging) and WINEARCH=win64
winetricks GUI enabled, using zenity 3.30.0
Executing mkdir -p /home/user/.local/share/wineprefixes
Executing w_do_call comctl32
Executing mkdir -p /home/user/.local/share/wineprefixes
Executing load_comctl32 
Executing wine /home/user/.cache/winetricks/comctl32/cc32inst.exe /T:C:\windows\Temp\_Versuch3 /c
Wine cannot find the ncurses library (libncurses.so.6).
Executing wine /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/temp/_Versuch3/x86/50ComUpd.Exe /T:C:\windows\Temp\_Versuch3 /c
Wine cannot find the ncurses library (libncurses.so.6).
Executing cp /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/temp/_Versuch3/comcnt.dll /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/system32/comctl32.dll
Using native,builtin override for following DLLs: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Versuch3\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Using builtin override for following DLLs when running winecfg.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Versuch3\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/temp/_Versuch3/override-dll.reg
Using builtin override for following DLLs when running explorer.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Versuch3\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/temp/_Versuch3/override-dll.reg
Using builtin override for following DLLs when running iexplore.exe: comctl32
Executing rm -rf /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_Versuch3\override-dll.reg
Wine cannot find the ncurses library (libncurses.so.6).
Executing rm /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/temp/_Versuch3/override-dll.reg
------------------------------------------------------
comctl32 install completed, but installed file /home/user/.local/share/wineprefixes/Versuch3/dosdevices/c:/windows/syswow64/comctl32.dll not found
------------------------------------------------------
```

**Comment by Golddouble** [comment]
Although the "Wine cannot find the ncurses library (libncurses.so.6)." issue is solved now, this is still an issue:
```
------------------------------------------------------
comctl32 install completed, but installed file /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/syswow64/comctl32.dll not found
------------------------------------------------------
```


See here:
```
$ winetricks
Executing mkdir -p /home/Golddouble
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 5c62bc038fd3ac7fa1e0d09123c61e1034cc5431719f5a1768dcb4bd91990cca with wine-5.6 (Staging) and WINEARCH=win64
winetricks GUI enabled, using zenity 3.30.0
Executing mkdir -p /home/Golddouble/.local/share/wineprefixes
Executing w_do_call comctl32
Executing mkdir -p /home/Golddouble/.local/share/wineprefixes
Executing load_comctl32 
Executing mkdir -p /home/Golddouble/.cache/winetricks/comctl32
Executing cd /home/Golddouble/.cache/winetricks/comctl32
Downloading https://downloads.sourceforge.net/project/pocmin/Win%2095_98%20Controls/Win%2095_98%20Controls/CC32inst.exe to /home/Golddouble/.cache/winetricks/comctl32
Executing cd /home/Golddouble
Executing wine /home/Golddouble/.cache/winetricks/comctl32/cc32inst.exe /T:C:\windows\Temp\_versuch /c
Executing wine /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/temp/_versuch/x86/50ComUpd.Exe /T:C:\windows\Temp\_versuch /c
Executing cp /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/temp/_versuch/comcnt.dll /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/system32/comctl32.dll
Using native,builtin override for following DLLs: comctl32
Executing rm -rf /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_versuch\override-dll.reg
Using builtin override for following DLLs when running winecfg.exe: comctl32
Executing rm -rf /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_versuch\override-dll.reg
Executing rm /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/temp/_versuch/override-dll.reg
Using builtin override for following DLLs when running explorer.exe: comctl32
Executing rm -rf /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_versuch\override-dll.reg
Executing rm /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/temp/_versuch/override-dll.reg
Using builtin override for following DLLs when running iexplore.exe: comctl32
Executing rm -rf /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing rm -rf /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest
Executing wine regedit C:\windows\Temp\_versuch\override-dll.reg
Executing rm /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/temp/_versuch/override-dll.reg
------------------------------------------------------
comctl32 install completed, but installed file /home/Golddouble/.local/share/wineprefixes/versuch/dosdevices/c:/windows/syswow64/comctl32.dll not found
------------------------------------------------------
```

**Comment by Golddouble** [comment]
?

**Comment by austin987** [comment]
There's nothing obviously wrong to me in that log and I can't reproduce it here.

Could be a bug in that version of wine/wine-staging. You might try 5.0/5.12 and/or wine-development. Or it may be in whatever `_versuch` verb you're calling.

Otherwise, you'll need to debug this yourself.
