### ISSUE TITLE
winetricks breaks if used with wine build with --enable-architectures=i386,x86_64 / winetricks_set_wineprefix()

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#2030]
In this setup, the prefix is 64-bit:
```
$ ls .wine/drive_c/
 ProgramData  'Program Files'  'Program Files (x86)'   users   windows

$ ls .wine/drive_c/windows/
command       globalization  inf        Microsoft.NET  performance  rundll.exe  system.ini  temp          twain_64     winhlp32.exe
explorer.exe  help           Installer  mono           regedit.exe  system      syswow64    twain_32      twain.dll    win.ini
Fonts         hh.exe         logs       notepad.exe    resources    system32    tasks       twain_32.dll  winhelp.exe  winsxs
```

But there's no `wine64` binary:
```
$ file /opt/oldwownew/wine-8.0/bin/* | grep -v 'shell script'
/opt/oldwownew/wine-8.0/bin/wine:           ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=2f7a2fb204c876e5afb2159a1fee1be79c3bb2eb, for GNU/Linux 3.2.0, with debug_info, not stripped
/opt/oldwownew/wine-8.0/bin/wine-preloader: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=f0ae5ff9d792141653276bf560fbd50d7fed5a8a, with debug_info, not stripped
/opt/oldwownew/wine-8.0/bin/wineserver:     ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4f79bb850598068f37fcc55ba1eac37e99c8e662, for GNU/Linux 3.2.0, with debug_info, not stripped
```

In this configuration, though, the wine binary is 64-bit, not 32-bit. wine-preloader/wineserver are also 64-bit, not 32-bit.

winetricks_set_wineprefix() needs to be adjusted for this case. Given that WINE can point to a shell script (for in tree builds), it's probably best to check the bitness of the wineserver binary (but this needs testing).

See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031649

**Comment by austin987** [comment]
From https://superuser.com/questions/791506/how-to-determine-if-a-linux-binary-file-is-32-bit-or-64-bit

`od -An -t x1 -j 4 -N 1` will return `01` or `02` for 32 versus 64-bit (od is part of coreutils, unlike file, which is slightly less common, and could return a wider variety of answers). Though that will return different info on OSX..

**Comment by Gcenx** [comment]
Using file would work on macOS see https://apple.stackexchange.com/questions/407467/how-to-determine-if-a-macos-program-on-apple-silicon-is-emulated-x86-or-native-a

**Comment by austin987** [comment]
So file returns multiple lines on OSX, unlike on GNU/Linux, so that's something else to account for.

Also need a way to portable way in shell to figure out the path to wineloader (may be a shell script/symlink). `readlink -f` may be nonportable, though I also don't think we need the `-f`.

**Comment by Gcenx** [comment]
Can't use `readlind -f` as the BSD version doesn't support `-f` or at least the macOS version doesn't

**Comment by Gcenx** [comment]
Going off your comment on the other issue it seems `readlink -f` might work on macOS Monterey (12.x) I did confirm it working on macOS Venture (13.x)

**Comment by austin987** [comment]
I made a [PR](https://github.com/austin987/winetricks/commit/05c43b58d2191958064516ec9406d837d8cf54e8) that works in very basic testing (for a classic win32 setup, an old style wow setup, and a new style wow setup).

Needs testing on OSX/BSD, for sure. Also needs testing with packages that have renamed wine or other less common setups.

At least mfc42 works. dotnet20 appears to, but hangs on --verify (probably a wine bug).

**Comment by Alexander88207** [comment]
Wine on FreeBSD doesn't havea preloader.

**Comment by austin987** [comment]
I've pushed a new version that avoids checking wine-preloader (just wine/wineserver):
https://github.com/austin987/winetricks/commit/8be3d32999f3b01dfbaa8b1048c660cae6ac7e59

Please test.

**Comment by austin987** [comment]
Another update, taking @theofficialgman's feedback into account:
https://github.com/austin987/winetricks/commit/73dc70c9d03a4171048c280bf956a981d6de4f21

**Comment by KenSharp** [comment]
Winetricks already initially makes an assumption about the bitness of the prefix from the existence of the `syswow64` directory:

```
    if test -d "${W_DRIVE_C}/windows/syswow64"; then
        if [ -n "${WINE64}" ]; then
            true
        elif [ "${WINE%??}64" = "${WINE}" ]; then
            WINE64="${WINE}"
        elif command -v "${WINE}64" >/dev/null 2>&1; then
            WINE64="${WINE}64"
        else
            WINE64="$(dirname "${WINE}")/"
            [ "${WINE64}" = "./" ] && WINE64=""
            WINE64="${WINE64}$(basename "${WINE}" | sed 's/^wine/wine64/')"
        fi
        WINE_ARCH="${WINE64}"
```

An easy check would be to see if the file actually exists:

```
if [ ! -x "${WINE64}" ]; then
	WINE64="${WINE}"
fi
```

It's a bold assumption, I know.

Of course this doesn't detect broken builds or wineprefixes transferred from another architecture, but that's what error messages are for.

**Comment by Gcenx** [comment]
> Winetricks already initially makes an assumption about the bitness of the prefix from the existence of the `syswow64` directory:
> 
> ```
>     if test -d "${W_DRIVE_C}/windows/syswow64"; then
>         if [ -n "${WINE64}" ]; then
>             true
>         elif [ "${WINE%??}64" = "${WINE}" ]; then
>             WINE64="${WINE}"
>         elif command -v "${WINE}64" >/dev/null 2>&1; then
>             WINE64="${WINE}64"
>         else
>             WINE64="$(dirname "${WINE}")/"
>             [ "${WINE64}" = "./" ] && WINE64=""
>             WINE64="${WINE64}$(basename "${WINE}" | sed 's/^wine/wine64/')"
>         fi
>         WINE_ARCH="${WINE64}"
> ```
> 
> An easy check would be to see if the file actually exists:
> 
> ```
> if [ ! -x "${WINE64}" ]; then
> 	WINE64="${WINE}"
> fi
> ```
> 
> It's a bold assumption, I know.
> 
> Of course this doesn't detect broken builds or wineprefixes transferred from another architecture, but that's what error messages are for.

The current checks can’t be used as the newer WoW64 builds by default only provide a `wine` binary that’s used for 32Bit & 64Bit launches.

**Comment by KenSharp** [comment]
> The current checks can’t be used as the newer WoW64 builds by default only provide a `wine` binary that’s used for 32Bit & 64Bit launches.

Very first line:

> Winetricks already initially makes an assumption about the bitness of the prefix from the existence of the`syswow64` directory

**Comment by Gcenx** [comment]
> > The current checks can’t be used as the newer WoW64 builds by default only provide a `wine` binary that’s used for 32Bit & 64Bit launches.
> 
> Very first line:
> 
> > Winetricks already initially makes an assumption about the bitness of the prefix from the existence of the`syswow64` directory

And again your not understanding the issue, that assumption won’t work for upstream wines newer WoW64.

**Comment by KenSharp** [comment]
```
if syswow64 exists
	then look for wine64
	if wine64 does not exist
		then use wine

if syswow64 does not exist
	use wine
```

I can't make it any more simple for you.

**Comment by Gcenx** [comment]
> ```
> if syswow64 exists
> 	then look for wine64
> 	if wine64 does not exist
> 		then use wine
> 
> if syswow64 does not exist
> 	use wine
> ```
> 
> 
>     
>   
> 
> I can't make it any more simple for you.

I literally have wineprefix that contain syswow64 and I onto have a `wine` binary, as I’d said already you’re not understand the issue.

**Comment by KenSharp** [comment]
> I literally have wineprefix that contain syswow64 and I only have a `wine` binary

Clever boy, so do I.

```
if wine64 does not exist
		then use wine
```

Honestly, a child has picked this up by now.

**Comment by Gcenx** [comment]
> > I literally have wineprefix that contain syswow64 and I only have a `wine` binary
> 
> Clever boy, so do I.
> 
> ```
> if wine64 does not exist
> 		then use wine
> ```

If that were a viable solution @austin987 would have done it already, that doesn't account to distro specific quirks.

> Honestly, a child has picked this up by now.

Looks like all you want to do is argue.

**Comment by KenSharp** [comment]
> If that were a viable solution @austin987 would have done it already, that doesn't account to distro specific quirks.

You clearly don't understand what Austin has done here.

```
elif [ "${_W_wow64_style}" = "new" ]; then
            WINE64="${WINE}"
```

So I'll explain it to you:

```
if syswow64 exists
	check the binary files for bitness
	if 64-bit use wine
	if 32-bit OR mixed-bit use wine64

if syswow64 does not exist
	use wine
```

That last section is the current behaviour.

In other words:

```
if syswow64 exists AND (( binaries are 32-bit OR mixed ))
	use wine
```
So the only time `wine64` is used, or needed, is if it and `syswow64` exists.

```
if syswow64 exists
	then look for wine64
	if wine64 does not exist
		then use wine
```

> Looks like all you want to do is argue.

By explaining things to you like a child? Okay, sweetheart. If you don't understand then just be quiet. And you do not understand. Not one bit.

**Comment by austin987** [comment]
@KenSharp chill. There's no reason to be antagonistic and rude. Those comments are not helpful.

If you want to be helpful, test/review the commit in https://github.com/Winetricks/winetricks/issues/2030#issuecomment-1623002125.

**Comment by KenSharp** [comment]
Yeah, sure, he's trolling and I'm being rude.

I've already looked at it: it's overly complicated which is why I had to explain it to your friend.

**Comment by austin987** [comment]
> Yeah, sure, he's trolling and I'm being rude.

I don't see his comments as trolling, but I think yours are.

> I've already looked at it: it's overly complicated which is why I had to explain it to your friend.

Then say that to me or on the review, no need to antagonize someone else. You weren't 'explaining', you were belittling. There is a world of difference between the two.

I've written in multiple comments/issues about why it's complicated, but you instead ignore all those comments and post a simple comment saying I've done it wrong. How is that helpful? Did you read all the associated bug reports/attempted PRs?

**Comment by KenSharp** [comment]
> And again your not understanding the issue

That's belittling, mate.

> simple comment saying I've done it wrong

Where does it say that?

Of course I've read it all. I've also explained in extreme detail why there's no point in messing about with the binaries if the only time they'll ever be checked is when `syswow64` is checked first anyway. I can't explain in any more clear way that you're just doing the same as falling back to `wine` if `wine64` doesn't exist.

There's not one comment explaining why this type of over-complication is needed.

This:

```
elif [ "${_W_wow64_style}" = "new" ]; then
            WINE64="${WINE}"
```

is exactly the same as this:

```
if [ ! -x "${WINE64}" ]; then
	WINE64="${WINE}"
fi
```

But now you know that the binaries may or may not match bitness. What does that achieve that's different? That information is never used again except for a warning:

`w_warn "You apppear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this."`

It's pretty obvious you think your way is the correct way, so go for it. This is why there's so many damned bugs.

**Comment by austin987** [comment]
> > simple comment saying I've done it wrong
> 
> Where does it say that?

https://github.com/Winetricks/winetricks/issues/2030#issuecomment-1650824955

> Of course I've read it all. I've also explained in extreme detail why there's no point in messing about with the binaries if the only time they'll ever be checked is when `syswow64` is checked first anyway. I can't explain in any more clear way that you're just doing the same as falling back to `wine` if `wine64` doesn't exist.
> 
> There's not one comment explaining why this type of over-complication is needed.

Then you didn't read it all:
https://github.com/Winetricks/winetricks/pull/2082#issuecomment-1605939364

> But now you know that the binaries may or may not match bitness. What does that achieve that's different? That information is never used again except for a warning:
> 
> `w_warn "You apppear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this."`

Exactly that. The warning is important, both for users, and for me or others reading the winetricks log.

The new wow method doesn't work quite the same. There are several bugs upstream about it. We may need different code paths in the future to accommodate that, but your simple patch won't allow that.

> It's pretty obvious you think your way is the correct way, so go for it.

I don't, actually. That's why I've pushed it and waited several weeks for feedback before pushing it.

> This is why there's so many damned bugs.

I have a full time job that isn't Wine. I do this in my spare time, for free, along with some others that contribute. I try hard to merge PRs as they come in. Other than that, my time is limited.

Funnily though, you've never sent a PR: https://github.com/Winetricks/winetricks/pulls?q=is%3Apr+author%3Akensharp+

So, frankly, if you think there are a ton of bugs, feel free to send a PR to fix them and I'll happily review them.

**Comment by theofficialgman** [comment]
@austin987 I've got no problem with the commit you made https://github.com/austin987/winetricks/commit/73dc70c9d03a4171048c280bf956a981d6de4f21

I'd be happy if it was pushed to master 😄

**Comment by Alexander88207** [comment]
Sorry that late answer.

When executing that on FreeBSD i do get:

od: wine: No such file or directory
od: cannot skip past end of input

and if i try to do stuff like vcrun2015 i get unknown arch messages.

**Comment by ProfDoof** [comment]
When running this on Pop!_OS 22.04 I also get `od: wine: No such file or directory`

I added 
```sh
        w_warn "WINESERVER to get binary arch of: ${WINESERVER}"
        w_warn "WINE to get binary arch of: ${WINE}"

        w_warn "Binary Arch of WINESERVER: ${_W_wineserver_binary_arch}"
        w_warn "Binary Arch of WINE: ${_W_wine_binary_arch}"
```
to my winetricks on line 5065 to get some more feedback and got 
```
od: wine: No such file or directory
------------------------------------------------------
warning: WINESERVER to get binary arch of: /usr/bin/wineserver
------------------------------------------------------
------------------------------------------------------
warning: WINE to get binary arch of: wine
------------------------------------------------------
------------------------------------------------------
warning: Binary Arch of WINESERVER: x86_64
------------------------------------------------------
------------------------------------------------------
warning: Binary Arch of WINE: ------------------------------------------------------
warning: Unknown file arch: 
------------------------------------------------------
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: f28471990044396173e71c90a1ed4afbbcd4a5d205e0b0e62660319eb52794fb with wine-8.15 (Staging) and WINEARCH=win64
winetricks GUI enabled, using zenity 3.42.1
```

**Comment by theofficialgman** [comment]
@austin987 there is a fatal flaw with your implementation that the above users are hitting. neither of your variables are guaranteed to be an absolute path to the binary which you intend to test.

if the variable contents isn't a path to the binary, you need to query the system for the path that it would result in when calling that binary name

eg:
```bash
if [ -e "${WINESERVER}" ]; then
  _W_wineserver_binary_arch="$(winetricks_get_file_arch "${WINESERVER}")"
else
  _W_wineserver_binary_arch="$(winetricks_get_file_arch "$(which "${WINESERVER}")")"
fi

if [ -e "${WINE}" ]; then
  _W_wine_binary_arch="$(winetricks_get_file_arch "${WINE}")"
else
  _W_wine_binary_arch="$(winetricks_get_file_arch "$(which "${WINE}")")"
fi
```
or something similar or you can just use which every time which will return the same path if a path is specified already
```bash
_W_wineserver_binary_arch="$(winetricks_get_file_arch "$(which "${WINESERVER}")")"
_W_wine_binary_arch="$(winetricks_get_file_arch "$(which "${WINE}")")"
```

**Comment by theofficialgman** [comment]
@austin987 so are you going to fix this critical issue or not?

**Comment by ausbin** [comment]
Unusual bit of user feedback: this issue was so frustrating that I punched an inanimate object. It was cathartic and I would recommend it to other users facing this issue

**Comment by vitlav** [comment]
I got an error about missed wine file on winetricks from 20231003:
```
++ winetricks_get_file_arch wine
++ _W_file=wine
+++ uname -s
++ '[' Linux = Darwin ']'
+++ tr -d '[:space:]'
+++ od -An -t x1 -j 0x12 -N 1 wine
od: wine: No such file or directory

```

**Comment by theofficialgman** [comment]
@vitlav yup. I gave the solution a month ago here https://github.com/Winetricks/winetricks/issues/2030#issuecomment-1705755913

Unfortunately it seems that @austin987 has ceased maintenance of winetricks. At least that is what it seems like right now.

**Comment by ProfDoof** [comment]
It seems like @austin987 is not actively doing development but does seem to be accepting commits or PRs so we could just PR it with a new issue.

**Comment by Chiitoo** [comment]
It's just one of those busy-with-other-things times I believe.  :]

vitlav, it will be better if you create a new issue for your issue, so that it can be tracked and acted upon better, instead of it being forgotten as a comment in a closed issue.

**Comment by randallpittman** [comment]
@Chiitoo , @vitlav, @ProfDoof, @theofficialgman, @aubin - Addressed in Issue #2143, PR #2147. Feel free to comment/contribute if there's a better implementation.

**Comment by melroy89** [comment]
Despite this issue being closed, I think the problem is still present on various distros now. Where they package wine in the new way, not creating a wine64 binary anymore in /usr/bin. But only a `wine` wrapper script, which winetricks can not handle correctly.

**Comment by psyhigh** [comment]
> if syswow64 exists
> 	then look for wine64
> 	if wine64 does not exist
> 		then use wine
> 
> if syswow64 does not exist
> 	use wine

hahaha you are right here on git and redit everybody is the smartest and you are idiot but noone cant say what to do so you can explain but they are to above you to read cuz you are stupit cuz you ask,,, omg these people are so condesendig some.. but fun fact noone ever saw a pussy they thin is distro error lol . wine64 an wine32 imposible to instal if you listen them i just tried abot 100 combos and now it works dont ask me how IDK i have a girl :))))

**Comment by melroy89** [comment]
I still this its an issue even in Debian 13 Trixie (latest LTS) for example..?


And warnings are still given despite the `-q` flag.
