### ISSUE TITLE
[Solved] Call from to unimplemented function api-ms-win-crt-math-l1-1-0.dll._except1, aborting

### ISSUE THREAD

**Issue by rboxeur** [Winetricks/winetricks#597]
The game "Grim Dawn" on Steam requires vcrun2105.
Unfortunately there is a missing DLL. We got this error

Call to unimplemented function api-ms-win-crt-math-l1-1-0.dll._except1, aborting

This DLL has to be copied and set
[winetricks_20105.txt](https://github.com/Winetricks/winetricks/files/99729/winetricks_20105.txt)

 as native.
Can you apply this  patch so it can be fixed?

After that the game works properly

**Comment by austin987** [comment]
Pull requests are a bit easier for future reference. Also, please avoid tabs, and match indentation.

I committed a fixed version here: https://github.com/Winetricks/winetricks/commit/016197d822db495df376407334d85f3b2e3b0f9c

Thanks for the patch

**Comment by alexforbes** [comment]
I'm afraid that this change doesn't seem to solve the issue for me.
The error remains the same.
This person seems to have had the same experience: http://ubuntuforums.org/showthread.php?t=2312935

**Comment by austin987** [comment]
Please file a new issue, and attach a log with winetricks -v vcrun2015

**Comment by brianinthered** [comment]
I am experiencing this exact error as well.  
**wine: Call from 0x7b83ea32 to unimplemented function api-ms-win-crt-math-l1-1-0.dll._except1, aborting**
I'm using the Steam version of Grim Dawn with PlayOnLinux and applied the vcrun2015 with this method:
**wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks 
WINEPREFIX=/home/booman/.PlayOnLinux/wineprefix/grimdawn ./winetricks -q vcrun2015**

Previously the game wouldn't even launch, but now it launched fine and actually gets to the menu.  But as described above, crashes after the initial cut-scene when loading the first level

**Comment by austin987** [comment]
Are you using a 64 bit prefix, by chance?

Is there a free download with this problem?

**Comment by brianinthered** [comment]
Nope, I always use a 32-bit wineprefix (virtual drive)
No free download or demo for Grim Dawn.
Previously Grim Dawn worked flawlessly until they updated to vcrun2015

**Comment by austin987** [comment]
Boo. How about a +loaddll trace (if you can attach as a file, that's preferable than in line, but GH can be screwy with that)?

**Comment by brianinthered** [comment]
I don't know how to do that in PlayOnLinux, but I can send a debug from launch to crash

**Comment by austin987** [comment]
https://wiki.winehq.org/FAQ#How_do_I_get_a_debug_trace.3F

Ask playonlinux if that doesn't help

**Comment by brianinthered** [comment]
Sorry, I keep forgetting to give this a try so you can see my log.

**Comment by austin987** [comment]
I just committed a fix from @boltronics for this, please retest.

**Comment by brianinthered** [comment]
Awesome!  I will definitely give Grim Dawn a test run again.
Thank you!

**Comment by brianinthered** [comment]
It works!!!
Thank you so much, I am so excited to play Grim Dawn in PlayOnLinux again!

**Comment by codyf86** [comment]
Yes that Commit fixed it, thank you! :)
