### ISSUE TITLE
Error on downloading msxml3.msi

### ISSUE THREAD

**Issue by Lenseth** [Winetricks/winetricks#777]
```
Executing w_do_call msxml3
Executing load_msxml3 
Executing cd /home/metalknuxx/.cache/winetricks/msxml3
Downloading https://download.microsoft.com/download/8/8/8/888f34b7-4f54-4f06-8dac-fa29b19f33dd/msxml3.msi to /home/metalknuxx/.cache/winetricks/msxml3
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Executing cd /home/metalknuxx
Executing cd /home/metalknuxx/.cache/winetricks/msxml3
Downloading https://web.archive.org/web/https://download.microsoft.com/download/8/8/8/888f34b7-4f54-4f06-8dac-fa29b19f33dd/msxml3.msi to /home/metalknuxx/.cache/winetricks/msxml3
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Executing cd /home/metalknuxx
------------------------------------------------------
sha256sum mismatch!  Rename /home/metalknuxx/.cache/winetricks/msxml3/msxml3.msi and try again.
------------------------------------------------------
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by qwertychouskie** [comment]
Should be fixed since the merging of https://github.com/Winetricks/winetricks/pull/775.

**Comment by Lenseth** [comment]
Got the file directly form the repository yesterday and the error is still there
msxml3.msi and WIN2KSP4_EN.EXE have those errors too

**Comment by qwertychouskie** [comment]
The PR was merged only 9 hours ago.

**Comment by austin987** [comment]
This should avoid the issue entirely:
https://github.com/Winetricks/winetricks/commit/36c9bae95cbf420095d0a8f804fc35c01aa7e815
