### ISSUE TITLE
Winetricks GUI just crashes itself, something to do with "track usage" that get sent to you guys.

### ISSUE THREAD

**Issue by frenchiveruti** [Winetricks/winetricks#867]
So, I'm using a Puppy Linux (Yea yea non-conventional yada yada) TahrPup 64 bits 6.0.5 based on Ubuntu OS.
I'm running wine 2.0.3 x64 from this topic: http://murga-linux.com/puppy/viewtopic.php?t=88711

When I run Winetricks, it generates the first GUI, but in the moment I press OK, regardless of the option, It closes.
Here's the LOG:
[winetrickslog.log](https://github.com/Winetricks/winetricks/files/1463995/winetrickslog.log)

If you need something else let me know.

**Comment by austin987** [comment]
AFAICT, the issue is that winetricks is being called with the argument 'TRUE', which is unknown, and it errors out:

```
+ winetricks_metadata_exists TRUE
+ test -f '/tmp/winetricks.j3hf3OQZ/w.root.545/metadata/*/TRUE.vars'
+ echo 'Unknown arg TRUE'
Unknown arg TRUE
+ winetricks_usage
+ case $LANG in
+ cat
Usage: /usr/sbin/winetricks [options] [command|verb|path-to-verb] ...
Executes given verbs.  Each verb installs an application or changes a setting.

Options:
    --force           Don't check whether packages were already installed
    --gui             Show gui diagnostics even when driven by commandline
    --isolate         Install each app or game in its own bottle (WINEPREFIX)
    --self-update     Update this application to the last version
    --update-rollback Rollback the last self update
-k, --keep_isos       Cache isos (allows later installation without disc)
    --no-clean        Don't delete temp directories (useful during debugging)
-q, --unattended      Don't ask any questions, just install automatically
-r, --ddrescue        Retry hard when caching scratched discs
    --showbroken      Even show verbs that are currently broken in wine
-t  --torify          Run downloads under torify, if available
    --verify          Run (automated) GUI tests for verbs, if available
-v, --verbose         Echo all commands as they are executed
-h, --help            Display this message and exit
-V, --version         Display version and exit

Commands:
list                  list categories
list-all              list all categories and their verbs
apps list             list verbs in category 'applications'
benchmarks list       list verbs in category 'benchmarks'
dlls list             list verbs in category 'dlls'
games list            list verbs in category 'games'
settings list         list verbs in category 'settings'
list-cached           list cached-and-ready-to-install verbs
list-download         list verbs which download automatically
list-manual-download  list verbs which download with some help from the user
list-installed        list already-installed verbs
prefix=foobar         select WINEPREFIX=/root/.local/share/wineprefixes/foobar
+ exit 1
```

Note that puppy linux on its own shouldn't pose a problem, but Wine discourages running as root. This is the second time I've seen that this week (root + winetricks), so I'll probably add a warning for it.

**Comment by frenchiveruti** [comment]
I see, well, puppy runs entirely on root so I can't really avoid that out.  
Is there any workaround?

**Comment by austin987** [comment]
Are you running from the gui? Does it does that if you just run 'winetricks' from a terminal?

**Comment by frenchiveruti** [comment]
Hi austin, this issue is the GUI closing itself, but winetricks works as intended when I run it from console, as root.  
I'm now trying if it has the same behaviour running from a user with no root privileges

**Comment by frenchiveruti** [comment]
Here are two more logs, one where I press "OK" and "OK". 
[winetrickslogOkOK.log](https://github.com/Winetricks/winetricks/files/1464125/winetrickslogOkOK.log)


The other one pressing "Cancel" "Cancel".
[winetrickslogcancel cancel.log](https://github.com/Winetricks/winetricks/files/1464126/winetrickslogcancel.cancel.log)

**Comment by frenchiveruti** [comment]
Here are two new output files from winetricks. Even running as a lesser user it doesn't really matter. It just closes the GUI without reason (that I can understand).
Regarding the "track usage window"

Here are two logs, one where I press "Ok" and "OK":
[winetrickslogOKOK.log](https://github.com/Winetricks/winetricks/files/1464128/winetrickslogOKOK.log)

And here's another one where I press "Cancel" and "Ok":
[winetrickslogCancel Ok.log](https://github.com/Winetricks/winetricks/files/1464129/winetrickslogCancel.Ok.log)

**Comment by austin987** [comment]
> /usr/sbin/winetricks: line 18844: /root/.cache/winetricks/track_usage: No such file or directory

try in latest git, https://github.com/Winetricks/winetricks/commit/fa07ae25fb8813b475e74190796925d18b491827 should fix that. Alternatively, run 'mkdir -p $HOME/.cache/winetricks' first.

**Comment by frenchiveruti** [comment]
Hi Austin, I'm using the latest version of winetricks (used winetricks --self-update) and I'm still getting a crashing GUI.
May it be related to the Window Manager I'm using?
I'm Using JWM and it doesn't support certain things like transparency.

**Comment by austin987** [comment]
@frenchiveruti It's possible, but I doubt it. Could you attach the terminal output/crash please?

**Comment by frenchiveruti** [comment]
Sure, would you mind setting me a command and I parse everything to a .log file for you.

**Comment by austin987** [comment]
Well, however you generated the .log files earlier. Something like:
```
$ winetricks -v > log.txt 2&>1  
```

**Comment by frenchiveruti** [comment]
Ok I got it, I issued:
```bash
$ winetricks -v &>> log.txt
```

And I got this file:
[log.txt](https://github.com/Winetricks/winetricks/files/1682546/log.txt)

With `winetricks --version`:
20171222-next - sha256sum: 01ebb56d22f54467343700eedfe283d82a47e67bbb6c2d68b7da743f41bb78a3



Hope this helps.
Thanks

**Comment by austin987** [comment]
@frenchiveruti nothing obvious. Try this:

```
$ winetricks -v --no-tmp &> log
$ grep tmp log
```

You should see something like:
```
++ sh /tmp/winetricks.CIPKXLR6/w.austin.25264/zenity.sh
```

Try running that manually and see if you get the same result / what it outputs.

**Comment by frenchiveruti** [comment]
I guess you meant 
```bash
$ winetricks -v --no-clean &> log
```
Because if `--no-tmp` outputs:
"unknown option --no-tmp"

So here's the output for 
```bash
$ winetricks -v --no-clean &> log.log
```
[log.log](https://github.com/Winetricks/winetricks/files/1682884/log.log)


The file that gets created (The zenity one) comes out without exec permissions.
I did `sh zenity.sh` and I got the same results, with this output:
`"TRUE|main|Select the default wineprefix|"`

**Comment by frenchiveruti** [comment]
Hello, I come back, winetricks now it's version 
`20190615 - sha256sum: b6e465841d1d7bf473d8ecd32ed7a18e0add817444bf54ec25e6c9465584c6e9`
I still run into the same issue, please let me know if there's anything I can provide for debugging
Greets

**Comment by austin987** [comment]
It's almost certainly an outdated/buggy zenity version. I tested in the latest puppy linux, and it works fine.

I'd file an issue with puppy.

**Comment by frenchiveruti** [comment]
Alright, thank you very much.
